### ISSUE TITLE
How to use hotstrings

### ISSUE THREAD

**Issue by megabugman** [kalekje/LNCHR-pub#3]
How to use hotrings in the script? Can you add an example in CommandsGenerator?

the "top" command seems not work, the code is missing.
Also some *.ahk files like eg ShowAHKScripts.ahk

Thank You!

**Comment by kalekje** [comment]
You should be able to just use the "k" type and type your hotstring in the next column with the Excel tool. I could make a variant that uses SendText instead of Send.

Those files are missing as you may have guessed, are in my local computer a folder above LNCHR. They're considered out of scope for this repo. 

A lot of these commands also send shortcuts that active some of the Windows PowerToys tools. https://learn.microsoft.com/en-us/windows/powertoys/
